FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY api/requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY api api/

EXPOSE 3004

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "3004"]
